<?php

namespace App\Http\Controllers;

use App\Grid\Grid;
use App\Models\Estudiante;
use Illuminate\Http\Request;

class EstudianteController extends Grid
{

    protected string $modelClass = Estudiante::class;

    protected string $title = 'Estudiantes';

    protected string $page = 'Estudiantes';

    protected function mounted()
    {
        parent::mounted(); // TODO: Change the autogenerated stub
    }
}
